import streamlit as st

st.title("Controle de parada de máquina")
nome_mecanico = st.selectbox('Selecione',['','MICHEL','UILIMI','ANDERSON','TALLES','DOUGLAS','ADILSON','TED','RICARDO'])

nome_maquina = st.selectbox('Selecione',['B-01', 'B-02', 'B-03', 'B-04', 'B-05', 'B-06', 'B-07', 'B-08', 'B-09', 'B-10', 'B-11',
'B-12', 'B-13', 'B-14', 'B-15', 'B-16', 'B-17', 'B-18', 'B-19', 'B-20', 'B-21', 'B-22'])

parada_maquina = st.selectbox('Selecione',['AFIAR FACAS', 'AJUSTE DE FOLGAS', 'AJUSTE DE SINCRONIZAÇÃO', 'AJUSTE DO PASSE DO CARRINHO', 
'AJUSTE MOLDES LATERAIS', 'AJUSTE NA BASE DO ELETRODO', 'AJUSTE SUPORTE DE ELETRODO', 'ALARME DE COLIZÃO ACIONADO', 'AMOLAR FACA', 'ARGOLA CRUZANDO',
'ARGOLA DESCENDO NA FORMAÇÃO', 'BOBINA TRAVADA', 'CAPTURA DOS SENSORES', 'CENTRALIZAÇÃO DA PINÇA INFERIOR', 'CONTROLE DE SOLDA', 
'EMPILHAMENTO DE MALHA', 'ELETRODO QUEBRADO', 'ENERGIA OSCILANDO', 'FALHA SENSOR ABERTURA DE PORTA', 'FALTA DE ENERGIA', 'LIMAR ELETRODO', 
'LIMPEZA DA MÁQUINA', 'MANUTENÇÃO CORRETIVA', 'MÁQUINA TRAVADA', 'PROBLEMA FORMAÇÃO DE ARGOLA', 'PROBLEMA TORRE DE SOLDA', 'PROBLEMAS DE SENSORES',
'REGULAGEM DA PINÇA', 'REGULAGEM DE MÁQUINA', 'REGULAGEM DE POUSSOIRS', 'REGULAGEM DO GLISSOIR', 'REGULAGEM TOURELA', 'RETIFICA DE ELETRODO', 
'RETIFICA DE FACA', 'SOLDA RUIM', 'TROCA DE AGULHA', 'TROCA DE BUCHA', 'TROCA DE CHAPAS', 'TROCA DE DEDINHO', 'TROCA DE EIXO', 'TROCA DE ELETRODO',
'TROCA DE FACA', 'TROCA DE FIO', 'TROCA DE MOLA DO SUPORTE DA PINÇA', 'TROCA DE PROGRAMA',
'TROCA DE ROLAMENTO', 'TROCA MOLDES LATERAIS', 'TROCA ROLAMENTO DE DISCO', 'NÃO SE APLICA'])
